package io.github.n08i40k.extera.gradle.extensions

import org.gradle.api.Action
import org.gradle.api.file.ConfigurableFileCollection
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.model.ObjectFactory
import org.gradle.api.provider.ListProperty
import org.gradle.api.provider.Property
import javax.inject.Inject

abstract class ExteraPluginExtension @Inject constructor(
    private val objects: ObjectFactory
) {
    /**
     * Plugin metadata.
     */
    abstract val pluginId: Property<String>
    abstract val pluginName: Property<String>
    abstract val pluginDescription: Property<String>
    abstract val pluginAuthor: Property<String>
    abstract val pluginVersion: Property<String>

    /**
     * Minimal supported exteraGram version.
     *
     * Example: `"12.1.1"`
     */
    abstract val minClientVersion: Property<String>

    /**
     * Entry class of plugin.
     *
     * Example: `"ru.n08i40k.streaks.Plugin"`
     */
    abstract val entryClass: Property<String>

    /**
     * Path to Telegram.jar generated by dex2jar.
     *
     * Example: `files("libs/Telegram.jar")`
     */
    abstract val telegramJar: RegularFileProperty

    /**
     * List of package prefixes that will be excluded from classpath.
     * Can be used to avoid classpath conflicts between plugin dependencies and client build.
     *
     * Example: `listOf("kotlin", "com.android.tools.r8")`
     */
    abstract val conflictingPackages: ListProperty<String>

    /**
     * List of files with proguard rules.
     */
    abstract val proguardFiles: ConfigurableFileCollection

    /**
     * Version of r8 that will be used to convert .jar to .dex and shrink unused code.
     *
     * Example: `"9.4.17"`
     */
    abstract val r8Version: Property<String>

    /**
     * Minimal Android SDK version.
     * Should be same as minSdk in `android` block.
     *
     * Example: `26`
     */
    abstract val minSdk: Property<Int>

    /**
     * Parent package every relocated package is moved under.
     *
     * Example: `"io.github.n08i40k.extera_shaded"`
     */
    abstract val shadedPackage: Property<String>

    abstract val relocations: ListProperty<RelocationSpec>

    /**
     * Directory the dex and plugin jar are written to.
     */
    abstract val outputDir: DirectoryProperty

    private fun newSpec(pkg: String): RelocationSpec =
        objects.newInstance(RelocationSpec::class.java, pkg.trimEnd('.'))

    /**
     * Relocates (shades) provided package name to `shadedPackage`.
     */
    fun relocate(vararg packages: String) {
        packages.forEach { relocations.add(newSpec(it)) }
    }

    /**
     * Relocates (shades) provided package name to `shadedPackage`.
     * Also, can exclude certain sub-packages or classes in the provided package from relocation.
     */
    fun relocate(pkg: String, action: Action<RelocationSpec>) {
        relocations.add(
            newSpec(pkg)
                .apply { action.execute(this) }
        )
    }
}