package io.github.exterastuff.plugin.extensions

import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.ListProperty

public abstract class TelegramExtension {
    private companion object {
        val DEFAULT_CONFLICTING_PACKAGES =
            listOf(
                "kotlin/",
                "kotlinx/coroutines/",
                "com/android/tools/r8/",
            )
    }

    /**
     * Path to Telegram.jar generated by dex2jar.
     *
     * Example: `files("libs/Telegram.jar")`
     */
    public abstract val jar: RegularFileProperty

    /**
     * List of package prefixes that will be excluded from classpath. Can be used to avoid classpath
     * conflicts between plugin dependencies and client build.
     *
     * Example: `listOf("kotlin", "com.android.tools.r8")`
     */
    public abstract val conflictingPackages: ListProperty<String>

    init {
        conflictingPackages.convention(DEFAULT_CONFLICTING_PACKAGES)
    }
}
