package io.github.exterastuff.gradle.plugin.tasks

import org.gradle.api.DefaultTask
import org.gradle.api.GradleException
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.ListProperty
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.InputFiles
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.PathSensitive
import org.gradle.api.tasks.PathSensitivity
import org.gradle.api.tasks.TaskAction
import org.gradle.work.DisableCachingByDefault
import org.objectweb.asm.ClassReader
import org.objectweb.asm.ClassVisitor
import org.objectweb.asm.ClassWriter
import org.objectweb.asm.FieldVisitor
import org.objectweb.asm.MethodVisitor
import org.objectweb.asm.Opcodes
import java.io.File
import java.nio.file.attribute.FileTime
import java.util.zip.Deflater
import java.util.zip.ZipEntry
import java.util.zip.ZipFile
import java.util.zip.ZipOutputStream

// now made by me.... still without love :(

/**
 * Timestamp written into every output entry.
 * Used to keep output byte-identical.
 */
private val ZIP_EPOCH = FileTime.fromMillis(315_532_800_000L)

/**
 * Matches `Lcom/example/Class$Child1<Any>` as `com/example/Class$Child1`
 * inside a type descriptor or a generic signature.
 */
private val TYPE_DESCRIPTOR = Regex("L([^;<]+)")

private val ALWAYS_EXCLUDED_PREFIXES = listOf("java/", "com/android/tools/r8/")

private val ZipFile.classEntries: Sequence<ZipEntry>
    get() = entries().asSequence()
        .filter { !it.isDirectory && it.name.endsWith(".class") }

/**
 * Adds nested classes into set.
 *
 * For example, when `com/example/Class$Child1$Child2` is passed,
 * only `com/example/Class$Child1$Class2` and `com/example/Class$Child1`
 * will be added to set.
 */
private fun MutableSet<String>.addInnerClasses(className: String?) {
    var name = className ?: return

    while (name.contains('$')) {
        add(name)
        name = name.substringBeforeLast('$')
    }
}

private fun MutableSet<String>.collectClassesFromDescriptor(descriptor: String?) {
    if (descriptor == null)
        return

    for (match in TYPE_DESCRIPTOR.findAll(descriptor)) {
        addInnerClasses(match.groupValues[1])
    }
}

@DisableCachingByDefault(because = "TODO")
abstract class ProcessTelegramJarTask : DefaultTask() {
    /**
     * Path to Telegram client jar that was generated by dex2jar by user.
     *
     * Declared as `@InputFiles` rather than `@InputFile` so a missing jar
     * will be reported correctly.
     */
    @get:InputFiles
    @get:PathSensitive(PathSensitivity.NONE)
    abstract val inputJar: RegularFileProperty

    /**
     * List of package name prefixes that needs to be excluded
     * from stripped jar.
     *
     * Example: `listOf("kotlin", "com.android.tools.r8")`
     */
    @get:Input
    abstract val excludedPrefixes: ListProperty<String>

    @get:OutputFile
    abstract val outputJar: RegularFileProperty

    @TaskAction
    fun run() {
        val input = inputJar.get().asFile

        if (!input.isFile)
            throw GradleException("${input.path} is missing, use dex2jar on Telegram apk to generate it")

        val output = outputJar.get().asFile
            .apply { parentFile.mkdirs() }

        var classCount = 0
        val prefixes = ALWAYS_EXCLUDED_PREFIXES +
                excludedPrefixes.get().map { it.replace('.', '/') }

        val accessMap = buildAccessMap(input)

        ZipFile(input).use { zip ->
            ZipOutputStream(output.outputStream().buffered()).use { out ->
                out.setLevel(Deflater.BEST_COMPRESSION)

                zip.classEntries
                    .filterNot { entry -> prefixes.any(entry.name::startsWith) }
                    .forEach { entry ->
                        val fixed = zip.getInputStream(entry)
                            .use { recomputeInnerClasses(it.readBytes(), accessMap) }

                        out.putNextEntry(
                            ZipEntry(entry.name)
                                .apply { lastModifiedTime = ZIP_EPOCH }
                        )
                        out.write(fixed)
                        out.closeEntry()

                        classCount++
                    }
            }
        }

        logger.lifecycle("write ${output.path} ($classCount classes)")
    }

    private fun buildAccessMap(inputJar: File): Map<String, Int> {
        val map = hashMapOf<String, Int>()

        ZipFile(inputJar).use { zip ->
            zip.classEntries
                .forEach { entry ->
                    zip.getInputStream(entry).use {
                        val reader = ClassReader(it)
                        map[reader.className] = reader.access
                    }
                }
        }

        return map
    }

    /**
     * Remaps inner classes to fix broken access flags.
     */
    private fun recomputeInnerClasses(bytes: ByteArray, accessMap: Map<String, Int>): ByteArray {
        val reader = ClassReader(bytes)

        val ref = LinkedHashSet<String>().apply {
            addInnerClasses(reader.className)
            addInnerClasses(reader.superName)
            reader.interfaces.forEach(::addInnerClasses)
        }

        reader.accept(
            object : ClassVisitor(Opcodes.ASM9) {
                override fun visitField(
                    access: Int,
                    name: String,
                    descriptor: String,
                    signature: String?,
                    value: Any?
                ): FieldVisitor? {
                    ref.collectClassesFromDescriptor(descriptor)
                    ref.collectClassesFromDescriptor(signature)
                    return null
                }

                override fun visitMethod(
                    access: Int,
                    name: String,
                    descriptor: String,
                    signature: String?,
                    exceptions: Array<out String?>?
                ): MethodVisitor? {
                    ref.collectClassesFromDescriptor(descriptor)
                    ref.collectClassesFromDescriptor(signature)
                    exceptions?.forEach(ref::collectClassesFromDescriptor)
                    return null
                }
            },
            ClassReader.SKIP_CODE
        )

        val writer = ClassWriter(0)

        reader.accept(
            object : ClassVisitor(Opcodes.ASM9, writer) {
                private val emitted = HashSet<String>()

                override fun visitInnerClass(
                    name: String,
                    outerName: String?,
                    innerName: String?,
                    access: Int
                ) {
                    emitted.add(name)
                    super.visitInnerClass(name, outerName, innerName, access)
                }

                override fun visitEnd() {
                    for (name in ref) {
                        if (!emitted.add(name))
                            continue

                        val simpleName = name.substringAfterLast('$')

                        val raw = accessMap[name] ?: (Opcodes.ACC_PUBLIC or Opcodes.ACC_STATIC)
                        val access = raw and Opcodes.ACC_SUPER.inv()

                        if (simpleName.isEmpty() || simpleName.first().isDigit()) {
                            super.visitInnerClass(name, null, null, access)
                            continue
                        }

                        super.visitInnerClass(
                            name,
                            name.substringBeforeLast('$'),
                            simpleName,
                            access or Opcodes.ACC_STATIC
                        )
                    }

                    super.visitEnd()
                }
            },
            0
        )

        return writer.toByteArray()
    }
}